### PR TITLE
Do not create development version tags.

### PR DESCRIPTION
**Pull request by davidlehn**
Untested example of how #5 could be addressed.

### CODE REVIEW

**Comment by davidlehn** [comment]
@mattcollier Any thoughts on this?  More and more of these dev tags are being created while this waits.

Should also consider removing every *-0 dev tag these scripts have created so far.

**Comment by mattcollier** [comment]
@davidlehn both `bower version prepatch` and `npm version prepatch` create these tags and I am inclined to continue going along with the default behavior.

Bower has deprecated the use of the `version` property in the bower.json and the next bower release should allow the `bower version` command to function completely based on tags.  When that happens, the pre-release `-0` tag may be relevant and useful.

**Comment by davidlehn** [comment]
`bower info` tells you prereleases are available, and `bower info --verbose` will show them.  But I'm guessing our process does not align with the intended use of these tags or the pre\* commands.  We have been bumping the version up after a release so when looking at or using repo code you can tell you're not using the last released version.  I think they mean those pre\* commands and the "-N" tags they generate to used at a useful point in time.  Right now we only tag commits that are like "Start x.y.(z+1)-0", which is always right after a x.y.z tag.  I can't think of any use for this and it adds to tag and commit message clutter.  If we start tagging actual prereleases, that's another matter.

**Comment by davidlehn** [comment]
@dlongley @msporny @mattcollier: Can we merge this?  I've been using it for a while for releases I do.  I'm unconvinced there is any reason to push a dev tag for the "start x.y.z" commit.  The downsides of tag clutter in UIs and on github are addressed by this patch.

**Comment by davidlehn** [comment]
Merged.  If this turns out to be an issue we can revisit and/or revert.

**Pull request merged**
